language: ruby
sudo: false
script: 'ci/travis.rb'
#FIXME: Remove bundler uninstall on Travis when https://github.com/bundler/bundler/issues/4493 is fixed.
before_install:
  - rvm @global do gem uninstall bundler --all --ignore-dependencies --executables
  - rvm @global do gem install bundler -v '1.11.2'
  - bundle --version
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
      env: "GEM=ar:mysql"
    - rvm: 2.0.0
      env: "GEM=ar:mysql"
    - rvm: ruby-head
      env: "GEM=ar:mysql"
    - env: "GEM=aj:integration"
  fast_finish: true
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"
